# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://open-archive.org
title: OpenArchive
email: info@open-archive.org
author: NatalieC510
description: OpenArchive - Preserving Mobilized Culture
tags: <meta name="google-site-verification" content="oCZV4khJNTu4MgQfe4PhbjSraiXKnnFvRi8Bpjtz_ss" />
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/open_archive
  - title: github
    url: https://github.com/openarchive
